jobs:
  check:
    if:
      ${{ github.event_name != 'pull_request' || !github.event.pull_request.draft
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v20
        with:
          github-token: ${{ secrets.NIX_GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Check Nix Flake
        run: "nix flake check \\\n  --all-systems \\\n  --no-pure-eval \\\n  --accept-flake-config\n"
name: Check
"on":
  pull_request:
    branches:
      - main
      - gh/*/*/base
  push:
    branches:
      - main
